#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

cat <<-EOF

Wit greit pauer kams
greit responsipiliti
  -- Pisdormen

EOF

} >&2
