#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export TERM=xterm-256color
export DEFAULT_USER=yvan
export MC_SKIN=$HOME/.config/mc/solarized.ini

pds () {php -d memory_limit=${1:=128}M -d opcache.enable=Off -S 0.0.0.0:8888 -t public public/index.php}
